import type { Metadata } from "next";
import { Inter, Knewave  } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Provider from "@/Provider";

const inter = Inter({ //шрифи для сайту
  variable: "--font-inter",
  subsets: ["latin"],
});

const knewave = Knewave({  //шрифи для сайту
  variable: "--font-knewave",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = { //мета дані для сайту
  title: "Web store",
  description: "Generated by create next app",
 
};

export default function RootLayout({ 
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${knewave.variable} antialiased`}
      >
        <Provider>

          {children} 
          
        </Provider>
        
      </body>
    </html>
  );
}
